-- MAVENMOVIES SQL ASSIGNMENT 1

--  LIST ALL THE DETAILS OF ACTORS
SELECT ACTOR_ID, CONCAT( FIRST_NAME, " ", LAST_NAME) AS FULL_NAME FROM ACTOR;

-- LIST ALL CUSTOMER DETAILS FROM DB
SELECT CUSTOMER_ID , STORE_ID, CONCAT( FIRST_NAME," ",LAST_NAME) AS NAME, EMAIL, ADDRESS_ID FROM CUSTOMER;

-- LIST DIFFERENT COUNTRIES
SELECT COUNTRY FROM COUNTRY;

-- DIAPLAY ALL ACTIVE CUSTOMERS
SELECT * FROM CUSTOMER;
SELECT CUSTOMER_ID , STORE_ID, CONCAT( FIRST_NAME," ",LAST_NAME) AS NAME FROM CUSTOMER WHERE ACTIVE=1;

-- LIST ALL RENTAL ID's FOR CUSTOMER WITH ID 1
SELECT * FROM RENTAL WHERE CUSTOMER_ID=1;

-- DISPLAY ALL THE FILMS WHOSE RENTAL DUARATION IS GREATER THAN 5
SELECT FILM_ID, TITLE FROM FILM WHERE RENTAL_DURATION > 5;

-- LIST THE TOTAL NUMBER OF FILMS WHOSE REOLACEMENT COST IS GREATER THAN $15 AND LESS THAN $20
SELECT FILM_ID, TITLE FROM FILM WHERE REPLACEMENT_COST BETWEEN 15 AND 20;

-- DISPLAY COUNT OF UNIQUE NAMES OF ACTOR
SELECT * FROM ACTOR;
SELECT COUNT(distinct(FIRST_NAME)) FROM ACTOR;

-- DISPLAY THE FIRST 10 RECORGS FROM THE CUSTOMER TABLE
SELECT * FROM customer LIMIT 10;

-- DISPLAY THE FIRST 3 RECORDS FROM THE CUSTOMER TABLE WHOSE FIRST NAME STARTS WITH begin
SELECT FIRST_NAME FROM CUSTOMER WHERE FIRST_NAME LIKE "B%" LIMIT 3;

-- Display the names of the first 5 movies which are rated as ‘G’
SELECT TITLE FROM FILM WHERE RATING = "G" LIMIT 5;

-- Find all customers whose first name starts with "a". 
SELECT * FROM customer WHERE FIRST_NAME LIKE "A%";

-- Find all customers whose first name ends with "a". 
SELECT * FROM customer WHERE FIRST_NAME LIKE "%A";

-- Display the list of first 4 cities which start and end with ‘a’ .
SELECT * FROM CITY WHERE CITY LIKE "A%A" LIMIT 4;

-- Find all customers whose first name have "NI" in any position
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE "%NI%";

-- FIND ALL THE CUSTOMER WHOSE FIRST NAME HAVE "R" IN THE SECOND POSITION
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE "_R%";

-- Find all customers whose first name starts with "a" and are at least 5 characters in length.
SELECT * FROM CUSTOMER;
 SELECT FIRST_NAME  FROM customer WHERE FIRST_NAME LIKE "A____";
 
 -- FIND ALL THE CUSTOMER WHOSE FIRST_NAME STARTS WITH 'A' AND ENDS WITH 'O'  
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE "A%O";

-- Get the films with pg and pg-13 rating using IN operator. 
SELECT * FROM FILM WHERE RATING IN ("PG" , "PG-13");

-- Get the films with length between 50 to 100 using between operator.
SELECT * FROM FILM WHERE LENGTH BETWEEN 50 AND 100;

-- Get the top 50 actors using limit operator
SELECT ACTOR_ID , CONCAT( FIRST_NAME," ", LAST_NAME ) AS NAME FROM ACTOR LIMIT 50;

-- Get the distinct film ids from inventory table.
SELECT distinct(FILM_ID) FROM INVENTORY; 










